name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]

env:
  CI_HOME_DIR: /home/runner
  HOLBA_OPT_DIR: ${{ env.CI_HOME_DIR }}/cache

jobs:
  build:
    name: CI Build
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        polyml: ['v5.7.1', 'v5.8']

    env:
      HOLBA_POLYML_VERSION: ${{ matrix.polyml }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: prepare cache
        run: ./install.sh
      - name: configure, make and test
        run: |
          ./configure.sh
          make


#- name: Cache multiple paths
#  uses: actions/cache@v2
#  with:
#    path: |
#      ~/cache
#      !~/cache/exclude
#      **/node_modules
#    key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

