name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]

env:
  HOLBA_OPT_DIR: $HOME/cache

jobs:
  build:
    name: CI scripts
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        polyml: ['v5.7.1', 'v5.8']

    env:
      HOLBA_POLYML_VERSION: ${{ matrix.polyml }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: install
        run: ./install.sh
      - name: configure
        run: ./configure.sh
      - name: make
        run: make


#- name: Cache multiple paths
#  uses: actions/cache@v2
#  with:
#    path: |
#      ~/cache
#      !~/cache/exclude
#      **/node_modules
#    key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

